// Base URL used for og:url and og:image references.
// Set NEXT_PUBLIC_SITE_URL in your deploy environment — falls back to the
// Vercel production URL so local omission doesn't break the build.
export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://paulsumido.com";

// Single shared OG image generated by src/app/opengraph-image.tsx.
// All feature pages reference this so there's one place to update the design.
export const OG_IMAGE = {
  url: `${SITE_URL}/opengraph-image`,
  width: 1200,
  height: 630,
  alt: "paul-explore — personal playground and portfolio",
};
