"use client";

import Link from "next/link";
import AnimatedNumber from "@/components/motion/AnimatedNumber";
import { FEATURES, THOUGHTS } from "@/app/_shared/featureData.data";
import { TEST_COUNT } from "@/app/_shared/testCount.generated";
import { SHELL } from "../shell";

const comma = (n: number) => n.toLocaleString("en-US");

/**
 * Every figure here is imported, not typed.
 *
 * TEST_COUNT is regenerated by the prebuild script on every build and the other
 * two are array lengths, so the strip cannot go stale and quietly overstate the
 * case. A guard test asserts against the same imports for the same reason.
 */
const FIGURES = [
  { value: TEST_COUNT, format: comma, caption: "tests, written first" },
  { value: FEATURES.length, format: String, caption: "apps, all of them live" },
  {
    value: THOUGHTS.length,
    format: String,
    caption: "write-ups on how they were built",
  },
];

/**
 * The claim check, directly under the hero.
 *
 * No cards. Three figures on a hairline with the vitals link closing the row,
 * which is the one number on this page I do not control: it comes from real
 * loads by real people.
 */
export default function Proof() {
  return (
    <section aria-labelledby="proof-title" className="border-y border-border">
      <h2 id="proof-title" className="sr-only">
        The numbers behind the claim
      </h2>
      <div className={`${SHELL} py-12`}>
        <dl className="grid gap-10 sm:grid-cols-3">
          {FIGURES.map((figure) => (
            <div key={figure.caption}>
              <dt className="sr-only">{figure.caption}</dt>
              <dd>
                <AnimatedNumber
                  value={figure.value}
                  format={figure.format}
                  className="font-display block text-4xl font-semibold tracking-tight tabular-nums sm:text-5xl"
                />
                <span className="mt-2 block text-sm text-muted">
                  {figure.caption}
                </span>
              </dd>
            </div>
          ))}
        </dl>
        <p className="mt-10 text-sm">
          <Link
            href="/vitals"
            className="text-primary-700 underline underline-offset-4 hover:opacity-80 dark:text-primary-300"
          >
            Real Core Web Vitals from this domain, measured live
          </Link>
        </p>
      </div>
    </section>
  );
}
