// AUTO-GENERATED by scripts/count-tests.mjs — do not edit by hand.
// Regenerated on every build via the `prebuild` script.
export const UNIT_TEST_COUNT = 2670;
export const E2E_TEST_COUNT = 59;
export const TEST_COUNT = 2729;
