// Counts test cases across the repo and writes the result to a generated TS
// module so the landing stats stay accurate without anyone editing a number by
// hand. Runs on `prebuild` (so Vercel regenerates on every deploy) and can be
// run manually with `pnpm stats`.
//
// Counting is static (regex over source), so it is an approximation: `.each`
// tables expand to multiple runtime cases we don't try to enumerate. The UI
// shows the count with a "+" suffix for exactly this reason. The script never
// fails the build — if anything goes wrong it logs and leaves the committed
// file in place.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/app/_shared/testCount.generated.ts");

// `it(` / `test(` (with optional .only/.skip/etc), not preceded by a word char
// or dot — so `habit(`, `retest(`, and `foo.test(` don't count.
const UNIT_RE = /(?<![\w.])(it|test)\s*(\.\w+)?\s*\(/g;
const E2E_RE = /(?<![\w.])test\s*(\.\w+)?\s*\(/g;

async function walk(dir, predicate, acc = []) {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return acc; // directory may not exist (e.g. e2e/ in some checkouts)
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
      await walk(full, predicate, acc);
    } else if (predicate(entry.name)) {
      acc.push(full);
    }
  }
  return acc;
}

async function countMatches(files, regex) {
  let total = 0;
  for (const file of files) {
    const src = await readFile(file, "utf8");
    const matches = src.match(new RegExp(regex.source, "g"));
    total += matches ? matches.length : 0;
  }
  return total;
}

async function main() {
  const unitFiles = await walk(
    join(ROOT, "src"),
    (name) => name.endsWith(".test.ts") || name.endsWith(".test.tsx"),
  );
  const e2eFiles = await walk(join(ROOT, "e2e"), (name) =>
    name.endsWith(".spec.ts"),
  );

  const unit = await countMatches(unitFiles, UNIT_RE);
  const e2e = await countMatches(e2eFiles, E2E_RE);

  const contents = `// AUTO-GENERATED by scripts/count-tests.mjs — do not edit by hand.
// Regenerated on every build via the \`prebuild\` script.
export const UNIT_TEST_COUNT = ${unit};
export const E2E_TEST_COUNT = ${e2e};
export const TEST_COUNT = ${unit + e2e};
`;

  await writeFile(OUT, contents, "utf8");
  console.log(
    `[count-tests] ${unit} unit + ${e2e} e2e = ${unit + e2e} tests → ${OUT.replace(ROOT + "/", "")}`,
  );
}

main().catch((err) => {
  console.warn(
    "[count-tests] failed, keeping existing generated file:",
    err?.message ?? err,
  );
  process.exit(0);
});
